### ISSUE TITLE
Unable to auto start rounds with Rev 2

### ISSUE THREAD

**Issue by jmkmoore** [taylorsussex/AutomaticReplayViewer#4]
When I switch the settings to Rev2, it does not recognize i'm in the replay theatre already.  It prompts me to start at the replay menu.  I've tried updating the pointers, but no action occurs after pressing start other than prompting to go to the replay menu.

**Comment by taylorsussex** [comment]
Tried switching around what pointers are used by the program

Let me know if this works for you

https://github.com/taylorsussex/AutomaticReplayViewer/releases/tag/v1.52
